apiVersion: v1
kind: ConfigMap
metadata:
  name: logipulse-config
  namespace: logipulse-ai
data:
  NODE_ENV: "production"
  ORDERS_SERVICE_PORT: "3001"
  TELEMETRY_SERVICE_PORT: "3002"
  AI_SERVICE_PORT: "3003"
  WEB_PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  POSTGRES_DB: "logipulse_db"
  MONGO_URI: "mongodb://mongodb-service:27017/logipulse_telemetry"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  GROQ_MODEL: "groq/compound-mini"
  CORS_ORIGIN: "http://logipulse.local"
