apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logipulse-ingress
  namespace: logipulse-ai
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "telemetry-service"
spec:
  rules:
    - host: logipulse.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web-service
                port:
                  number: 3000
          - path: /api/orders
            pathType: Prefix
            backend:
              service:
                name: orders-service
                port:
                  number: 3001
          - path: /api/telemetry
            pathType: Prefix
            backend:
              service:
                name: telemetry-service
                port:
                  number: 3002
          - path: /socket.io
            pathType: Prefix
            backend:
              service:
                name: telemetry-service
                port:
                  number: 3002
          - path: /api/ai
            pathType: Prefix
            backend:
              service:
                name: ai-analytics-service
                port:
                  number: 3003
