apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service-deployment
  namespace: logipulse-ai
  labels:
    app: orders-service
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: orders-service
  template:
    metadata:
      labels:
        app: orders-service
    spec:
      containers:
        - name: orders-service
          image: logipulse/orders-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: logipulse-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: logipulse-config
                  key: DB_PORT
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: logipulse-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: logipulse-secrets
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: logipulse-config
                  key: POSTGRES_DB
            - name: RABBITMQ_URI
              valueFrom:
                secretKeyRef:
                  name: logipulse-secrets
                  key: RABBITMQ_URI
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
  namespace: logipulse-ai
spec:
  selector:
    app: orders-service
  ports:
    - port: 3001
      targetPort: 3001
