apiVersion: v1
kind: Secret
metadata:
  name: logipulse-secrets
  namespace: logipulse-ai
type: Opaque
stringData:
  POSTGRES_USER: "logipulse_user"
  POSTGRES_PASSWORD: "logipulse_password"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASS: "guest"
  RABBITMQ_URI: "amqp://guest:guest@rabbitmq-service:5672"
  GROQ_API_KEY: "gsk_placeholder_key"
  TAVILY_API_KEY: "tvly_placeholder_key"
